### PR TITLE
convert to go modules

### PR DESCRIPTION
**Pull request by v1sion**
- Remove `go dep` dependency
- Convert to `go mod`
- Remove unnecessary `go dep` steps from ci

### CODE REVIEW

**Comment by v1sion** [comment]
@bboreham are you able to take a look?
The build part of the ci is failing as it tries to push the image and can't find the credentials, shouldn't the `push image` step occur just on `master`?
Im happy to make that change, even though i don't have that much experience with circleci

**Comment by bboreham** [comment]
>  shouldn't the push image step occur just on master?

It does. But the login step is above the if-statement.  Looks like a mistake.

**Comment by v1sion** [comment]
Oh i see it now, will move that login inside the if condition

**Comment by v1sion** [comment]
looks good now 🎉

**Review by bboreham — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
