### PR TITLE
feat: add multi-architecture build

### PR DESCRIPTION
**Pull request by charlie-haley**
Adding multi-architecture docker build using buildx

### CODE REVIEW

**Comment by charlie-haley** [comment]
realised this still wont work, converting to draft for now, going to try running locally

**Comment by xvzf** [comment]
Hey guys, is there an update on this one? :)

**Comment by kingdonb** [comment]
Thanks for submitting this PR! I've been meaning to learn about building multi-arch images, at a glance this LGTM and is a straightforward change, but I'm going to give it a quick try before I approve it for merging (since I've never used Watch.)

**Comment by kingdonb** [comment]
I'm not familiar with the finer points of CircleCI workflows, but I don't see anything in this change that looks objectionable.

👍 will merge this now. Thanks again.

**Review by kingdonb — APPROVED** [review]
👍

**Comment by kingdonb** [comment]
(Looks like there is no versioning or release workflow on this repo, so I guess we just merge it and that is it.)

**Pull request merged**
