### PR TITLE
Update alpine to 3.12

### PR DESCRIPTION
**Pull request by v1sion**
Update alpine to 3.12 to fix some vulnerabilities reported by container scanning tool

### CODE REVIEW

**Comment by fpytloun** [comment]
:+1: please merge this, Alpine 3.7 is obsolete and has security vulnerability in musl.

**Comment by diraol** [comment]
Well, I guess this could already go to 3.13

**Comment by v1sion** [comment]
> Well, I guess this could already go to 3.13

I dont even know if this is maintained any more. I create this PR on Jun 2020 🤷

**Review by mcsimk — APPROVED** [review]

**Comment by mcsimk** [comment]
@bboreham gentle ping..

**Comment by v1sion** [comment]
thank you @mcsimk

**Comment by bboreham** [comment]
Thanks for the PR.  Now CI is broken trying to build `dep`; if you'd like to have a go at that be my guest.
(e.g. convert to Go Modules)

**Comment by v1sion** [comment]
No worries, I will take a look to see what i can do

**Pull request merged**
